name = "mpizenberg/token-cred"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'mpizenberg/token-cred'"

[repository]
user = "mpizenberg"
project = "token-cred"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
