name = "mpizenberg/aiken-token-cred"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Use unique Cardano native tokens as credentials"

[repository]
user = "mpizenberg"
project = "aiken-token-cred"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
