name = "mpizenberg/cardano-badges"
version = "0.0.0"
compiler = "v1.1.16"
plutus = "v3"
license = "Apache-2.0"
description = "Use unique Cardano native tokens as credentials"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "1e419f1d845bc1f13935c56a342523af58839046"
source = "github"

[config]
